
base:
  verbose: 1
  save_path: "."
  seed: 42069
  device: "cuda:0"

dataset:
  loc: "/home/data2/tanminh/Evaluate_FIQA_EVR/data/processed_CPLFW/images"

dataloader:
  params:
    batch_size: 8

model:
  config: "models/quality_model/DiffFIQA/DiffFIQA/diffiqa_r/configs/model_config.yaml"
  weights: "/home/data2/tanminh/Evaluate_FIQA_EVR/pretrained/diffiqa_r.pth"
